### ISSUE TITLE
Centos 8

### ISSUE THREAD

**Issue by servergeeks** [okd-community-install/installcentos#175]
Hi guys,

Anyone here managed to get this ported/working on centos 8 ? 

Thanks!

br

**Comment by slaterx** [comment]
Hi,

According to https://docs.okd.io/latest/install/prerequisites.html and https://access.redhat.com/articles/2176281, OpenShift/OKD 3.x is released only for RHEL/CentOS 7.

**Comment by servergeeks** [comment]
Hi @slaterx,

Thanks for the link! So this would be working in openshift v4 running on centos 8.

br
